export const FETCH_TESTS_REQUEST = 'FETCH_TESTS_REQUEST';
export const FETCH_TESTS_SUCCESS = 'FETCH_TESTS_SUCCESS';
export const FETCH_TESTS_FAILURE = 'FETCH_TESTS_FAILURE';

export const FETCH_TEST_REQUEST = 'FETCH_TEST_REQUEST';
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS';
export const FETCH_TEST_FAILURE = 'FETCH_TEST_FAILURE';
export const TEST_CHECK_ANSWER = 'TEST_CHECK_ANSWER';
export const TEST_NEXT_QUESTION = 'TEST_NEXT_QUESTION';
export const TEST_FINISHED = 'TEST_FINISHED';
export const TEST_RESET = 'TEST_RESET';

export const ADD_TEST_SETTINGS = 'ADD_TEST_SETTINGS';
export const ADD_TEST_QUESTION = 'ADD_QUESTION';
export const CREATE_TEST_REQUEST = 'CREATE_TEST_REQUEST';
export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS';
export const CREATE_TEST_FAILURE = 'CREATE_TEST_FAILURE';
export const TEST_CREATOR_RESET = 'TEST_CREATOR_RESET';


export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';



